//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategori
    {
        public kategori()
        {
            this.alt_kategori = new HashSet<alt_kategori>();
        }
    
        public int kategori_id { get; set; }
        public string kategori_ad { get; set; }
        public Nullable<bool> aktif { get; set; }
    
        public virtual ICollection<alt_kategori> alt_kategori { get; set; }
    }
}
