//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public kullanici()
        {
            this.kullanici_skor = new HashSet<kullanici_skor>();
        }
    
        public int kullanici_id { get; set; }
        public string kullanici_adi { get; set; }
        public string kullanici_mail { get; set; }
        public string kullanici_sifre { get; set; }
        public Nullable<bool> aktif { get; set; }
        public string yetki { get; set; }
    
        public virtual ICollection<kullanici_skor> kullanici_skor { get; set; }
        public virtual kullanici_soru_cevap kullanici_soru_cevap { get; set; }
    }
}
