//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class soru_secenek
    {
        public soru_secenek()
        {
            this.kullanici_soru_cevap = new HashSet<kullanici_soru_cevap>();
        }
    
        public int secim_id { get; set; }
        public Nullable<int> soru_id { get; set; }
        public string dogru_cevap { get; set; }
    
        public virtual ICollection<kullanici_soru_cevap> kullanici_soru_cevap { get; set; }
        public virtual soru soru { get; set; }
    }
}
