//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici_skor
    {
        public int skor_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<int> eniyi_skor { get; set; }
    
        public virtual kullanici kullanici { get; set; }
    }
}
