//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test2Entities2 : DbContext
    {
        public test2Entities2()
            : base("name=test2Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alt_kategori> alt_kategori { get; set; }
        public DbSet<kategori> kategori { get; set; }
        public DbSet<kullanici> kullanici { get; set; }
        public DbSet<kullanici_skor> kullanici_skor { get; set; }
        public DbSet<kullanici_soru_cevap> kullanici_soru_cevap { get; set; }
        public DbSet<secenekler> secenekler { get; set; }
        public DbSet<sinav_tablo> sinav_tablo { get; set; }
        public DbSet<soru> soru { get; set; }
        public DbSet<soru_secenek> soru_secenek { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
