//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class secenekler
    {
        public secenekler()
        {
            this.soru_secenek = new HashSet<soru_secenek>();
        }
    
        public int secenek_id { get; set; }
        public Nullable<int> soru_id { get; set; }
        public string secenek { get; set; }
    
        public virtual ICollection<soru_secenek> soru_secenek { get; set; }
    }
}
