//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odev.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class soru
    {
        public soru()
        {
            this.kullanici_soru_cevap = new HashSet<kullanici_soru_cevap>();
            this.sinav_tablo = new HashSet<sinav_tablo>();
            this.soru_secenek = new HashSet<soru_secenek>();
        }
    
        public int soru_id { get; set; }
        public string soru_ad { get; set; }
        public Nullable<int> alt_kategori_id { get; set; }
        public Nullable<bool> aktif { get; set; }
    
        public virtual alt_kategori alt_kategori { get; set; }
        public virtual ICollection<kullanici_soru_cevap> kullanici_soru_cevap { get; set; }
        public virtual ICollection<sinav_tablo> sinav_tablo { get; set; }
        public virtual ICollection<soru_secenek> soru_secenek { get; set; }
    }
}
